- python/pyAero_problem.py
- python/pyStruct_problem.py
Sets do not maintain order, so when we loop over the items we may go over them in different orders not just when running the code at different times, but also between procs under MPI. Python 2 uses hashes to implicitly order items so things were kept under control, but python 3's behavior is random and this caused MPI issues in pyaerostructure (there is a corresponding fix/PR there). Here we make everything into _sorted_ lists so that every proc will have the same order, every time we run the same code.
> changed evalfuncs in aero and struct problems to sorted lists

- baseclasses/BaseRegTest.py
the testframework was hanging when a test failed with multiple procs.
This is what was happening for https://github.com/mdolab/adflow/pull/47
> fixed mpi hanging cause by single proc err

- baseclasses/BaseRegTest.py
- tests/test_BaseRegTest.py
This PR added a new keyword option `compare` when using the various add functions except for the `add_dict` function. If not in training mode, setting `compare=True` will compare an existing value with what's being added, instead of adding a new value. This is useful when the tests generate two values that should match. Instead of adding both to the reference file, we can now add just one, and use the `check=True` option to check the other value against it.
I added a few new tests.
> Add compare function when training

- baseclasses/BaseSolver.py
- baseclasses/__init__.py
- baseclasses/pyAero_problem.py
- baseclasses/pyAero_solver.py
- baseclasses/pyFieldPerformance_problem.py
- baseclasses/pyStruct_problem.py
- baseclasses/pyWeight_problem.py
- baseclasses/utils.py
- tests/test_BaseSolver.py
- tests/test_CaseInsensitve.py
This PR does the following:
- Added `CaseInsensitiveSet` and updated `CaseInsensitiveDict`
- Added tests for those
- Switched immutable options to use `CaseInsensitiveSet`
- Added support for deprecated options
- Both immutable and deprecated options can be passed in when the class is created. I have also added some tests for this
- Minor string/formatting fixes
Nothing in this PR should break backwards compatibility.
I have added a few tests
> Added Deprecated Options

- tests/test_BaseSolver.py
BaseSolver can handle options that accept multiple types if a tuple of types is provided in the default options. This is one way to address the second point in #26. I added a test to show that this works.
> Added multitype BaseSolver test

- baseclasses/BaseSolver.py
- tests/test_BaseSolver.py
I added a function `BaseSolver.pp()` which will print on the root proc if `self.comm` is defined. I also updated the printing functions `printCurrentOptions()` and `printModifiedOptions()` to use this function. Also added tests for these.
I added tests for the two functions that now use `self.pp()`.
> Added root print function

- baseclasses/BaseSolver.py
- baseclasses/__init__.py
- baseclasses/pyAero_solver.py
- tests/test_BaseSolver.py
With the additions of `self.comm` in PR #29, then if the user defines `self.comm` in a child class before calling the BaseSolver `__init__` then self.comm will get overwritten with None.
This PR adds a `comm` argument in the `BaseSolver.__init__` function. This avoids having to define a `self.comm` elsewhere in child classes.
It also add a `informs` member variable (with a small test) as well as updates the argument list with a consistent camelCase variable.
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.
> Basesolver init function now accepts a comm

- baseclasses/BaseSolver.py
- baseclasses/__init__.py
- baseclasses/pyAero_solver.py
- tests/test_BaseSolver.py
This PR adds a flag called `checkDefaultOptions`, which is used to tell BaseSolver not to do error checking against the default options when using `setOption`. This is useful when the default options are not the complete set, which could be the case when wrapping an external solver. In that case, it would be preferable to let the external solver handle its own options rather than hard-coding the options within the wrapper. The flag would tell `BaseSolver` not to perform error checking, instead letting the external solver handle that on its own.
This PR also added an option `caseSensitiveOptions`, which will force the options to be case sensitive.
I added a new test.
> Added `checkDefaultOptions`

- baseclasses/BaseSolver.py
- tests/test_BaseSolver.py
This PR makes the error messages a bit more helpful when an invalid option is used. It uses the build in function `get_close_matches` to suggest the closest option name to the one entered.
I added a new test
> Added a guess if option name is invalid

- baseclasses/BaseRegTest.py
- baseclasses/BaseSolver.py
- baseclasses/__init__.py
- tests/test_BaseRegTest.py
- tests/test_BaseSolver.py
This PR adds the ability for BaseRegTest to store metadata. This is a dictionary which is never used in testing, i.e. compared, but is used to store auxiliary information such as solver options. If present, it will be stored as the last key in the JSON file, and can be added/retrieved via dedicated API.
I have added a test to highlight the usage.
> Add metadata to BaseRegTest

- baseclasses/utils.py
- tests/test_BaseSolver.py
- tests/test_CaseInsensitve.py
Closes #37.
The implementation involves storing `self.map` which contains a dictionary for looking up the lower-case and capitalized keys. Any time a new key is added (initialization or subsequently) that capitalization is preserved and cannot be changed, but all comparisons are done with the lower-case values.
Now, for example when printing the options, you get:
```
'+----------------------------------------+'
'|           All test Options:            |'
'+----------------------------------------+'
{'boolOption': True,
'floatOption': 200.0,
'intOption': 3,
'listOption': [],
'multiOption': {},
'strOption': 'str1'}
```
where capitalization from initialization is maintained.
I slightly modified the existing …
> Updated containers to preserve capitalization on initialization

- baseclasses/utils.py
- setup.py
- tests/test_CaseInsensitve.py
Changes in #38 (specifically the fact that `__setitem__` and `__getitem__` now require the `self.map` attribute) meant that MPI operations based on pickling failed. I'm not entirely sure what's going on, but I suspect it's something to do with the fact that `self.map` is not available when picking these methods (maybe [the note here](https://docs.python.org/3/library/pickle.html#object.__setstate__) is relevant). Anyways, I had to implement `__new__` as suggested and now it works. I have added a bcast test. Note that `CaseInsensitiveSet` is unaffected since it does not have these two methods. I have no idea why these two methods specifically were causing problems...
I have added two tests.
_Put an `x` in …
> Fixed bcast error

- baseclasses/BaseSolver.py
For strings, `BaseSolver.pp()` should call `print` if `obj` is a string, otherwise call `pprint`.
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.
> changed pp to use pprint only if obj is not string

- baseclasses/BaseRegTest.py
- baseclasses/__init__.py
- baseclasses/pyWeight_problem.py
- tests/test_BaseRegTest.py
- tests/test_CaseInsensitve.py
`baseclasses` has two optional dependencies:
- `pygeo` used by `WeightProblem`
- `mpi4py` used by `BaseRegTest`
However, both of these are optional, i.e. there are some functionalities in these classes that can be used without the additional module. This PR improves this by suppressing the warning until the function requiring the optional dependency is actually called, whereby an Error is raised. I also fixed `BaseRegTest` which basically didn't work previously without `mpi4py`.
This PR is motivated by mdolab/pyoptsparse#213.
No new tests, but I verified that the same tests pass in an environment without `pygeo` or `mpi4py`.
> Updated optional dependencies

- baseclasses/decorators.py
- tests/test_BaseRegTest.py
- tests/test_BaseSolver.py
- tests/test_CaseInsensitve.py
I added a decorator `require_mpi` which can be used to skip a test that has a dependency on MPI. I also made a general constructor which can be used to skip tests based on availability of any Python package, so this can be used downstream in MACH repos (e.g. ESP tests in pygeo).
I did test locally in an environment without `mpi4py` that the decorator works as expected.
> Added `require_mpi` decorator for testing

- baseclasses/pyMission_problem.py
- baseclasses/utils.py
- tests/test_CaseInsensitve.py
I recently discovered abstract base classes in Python, and they seem like the correct approach for implementing these containers, since it's very clear which methods need to be implemented and which you get for free via inheritance. See for example [this article](https://treyhunner.com/2019/04/why-you-shouldnt-inherit-from-list-and-dict-in-python/) for a relevant discussion. Overall I think this is a much better implementation than what we had before, i.e. directly inheriting `dict` and `set`. A few things to note:
- I added a few new tests
- I added type annotations
- I clarified in docstrings that the initial capitalization is _persistent_, meaning `update()` etc. with a different capitalization will not replace it. I think this is the behaviour we want in relation to options …
> Updated containers to use ABC

- baseclasses/utils.py
- tests/test_CaseInsensitve.py
Closes #53. Turns out this was super easy, and I just had to make `repr` use the `pformat` function, which is the function that does the `pprint` formatting without printing anything out. I also added tests to check that the output strings are as expected.
I added two tests.
> Fix pprint for custom containers

- baseclasses/decorators.py
The skip test decorator prints a message if a required module is not found. There was a small bug where the message would simply say "None is not installed" since I overwrite the name of the module. This has now been fixed.
Create an environment without `mpi4py` and run the tests for `baseclasses` with `testflo . -v`. You should see messages such as `mpi4py is not installed" instead of `None is not installed".
> Fixed module name printed as None in decorator message

- baseclasses/utils/fileIO.py
- tests/test_fileIO.py
This fixes a bug where the whole script would crash because to many file handles were opened:
```
".../baseclasses/utils/fileIO.py", line 236, in redirectingIO
OSError: [Errno 24] Too many open files
```
~~Depends on your testing-requirements (see below)~~. I would be happy if this could be merged asap.
~~I tried implementing a test. But it is not that easy because it messes with the stdout and stderr. I personally understand the whole testing part to little to implement this properly.~~
I managed to implement a test that fails before the fix, but succeeds after it. 
But one can test it manually with this:
```
from mpi4py import MPI
from baseclasses.utils import redirectingIO
for i in range(2048):
with redirectingIO(open('test.out', 'a')):
print(f'test_{i}')
print('finished')
```
> Redirect fix

- baseclasses/problems/pyAero_problem.py
This fixes a bug where `_set_aeroDV_val` does not actually set the value. As far as I can tell, this bug/fix does not affect standard optimizations or much else in our codebase. However, the current code might cause problems if someone expects aero DVs to be updated when the AeroProblem is updated.
The regression occured on this commit https://github.com/mdolab/baseclasses/commit/1e2f3895d4c0ad7e0785c4ff47f916ed9fa2b675
I also thought this might be related to mdolab/adflow#208, but I don't think it is.
1-2 days
> Fixed aeroDV value setting

- baseclasses/utils/__init__.py
- baseclasses/utils/utils.py
- tests/test_utils.py
This PR adds a very simple parser to parse string formats. This parser can be used to extract information for different str formats, such as width and sign, for printing to stdout. 
No rush
> Adding a simple parser to parse string format

- baseclasses/problems/FluidProperties.py
- baseclasses/problems/pyFieldPerformance_problem.py
- baseclasses/testing/pyRegTest.py
- doc/conf.py
Minor changes to the docstrings of a few files. I also added a brief description of the `FluidProperties` class.
ASAP, it will fix the failed style checks for #89
> Updating docstrings to latest flake8 version

- baseclasses/solvers/pyAero_solver.py
This PR adds capability to set custom pointsets when adding DVGeo to the aero solver. The custom pointsets are provided in a dict where keys are the corresponding family names in the solver and values are the custom kwargs passed with those pointsets. See the relevant ADflow PR: https://github.com/mdolab/adflow/pull/299
> Custom ptsets

- baseclasses/__init__.py
- baseclasses/testing/pyRegTest.py
This resolves a longstanding issue where any package that depends on baseclasses would import mpi4py if available, which can cause a lot of different side effects. This now wraps all those calls inside modules/functions so that it's only imported as necessary.
> Remove mpi4py import on module import
