mdolab/baseclasses

- python/BaseRegTest.py
Added the option `check_arch` to the init, for packages that require both real and complex builds of PETSc to run all regression tests.
> added PETSc arch checking/setting to BaseRegTest

- setup.py
For workshop issue "Remove overly restrictive dependency versions"
> Remove overly restrictive dependency versions

- baseclasses/BaseRegTest.py
I identified a couple of bugs in the reg testing baseclass
- Training was not writing a new json file (it was just ignoring the tests)
- If a referenced array changes during training then the json file will reflect the new value, not the value at the time it was added to the db
None
> Fix reg testing bugs

- baseclasses/BaseSolver.py
- baseclasses/FluidProperties.py
- baseclasses/ICAOAtmosphere.py
- baseclasses/__init__.py
- baseclasses/pyAeroStruct_problem.py
- baseclasses/pyAero_geometry.py
- baseclasses/pyAero_problem.py
- baseclasses/pyAero_solver.py
- baseclasses/pyEngine_problem.py
- baseclasses/pyFieldPerformance_problem.py
- baseclasses/pyLG_problem.py
- baseclasses/pyMission_problem.py
- baseclasses/pyStruct_problem.py
- baseclasses/pyTransi_problem.py
- baseclasses/pyWeight_problem.py
- baseclasses/utils.py
- tests/test_BaseSolver.py
This PR is part of an [effort](https://github.com/mdolab/private-docs/issues/194) to improve the options handling in our codes. 
The main changes are to BaseSolver to allow the default options dictionary to include a list of possible choices for an option (if applicable). If a list is provided, the user input is checked against the list to make sure the value is valid. These changes are backwards compatible.
Some classes that were duplicated across files have also been moved into a separate file, `utils.py`.
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.
> Update BaseSolver options handling

- README.md
- baseclasses/__init__.py
- setup.py
This PR changes several things in preparation for PyPI release
- Updated `setup.py` and `README`
- incremented patch version
Publishing `baseclasses` on PyPI has several benefits
- pyOptSparse can switch to using these base classes to avoid code duplication, while still allowing dependencies to be installed automatically by pip without cloning/building from source
- building documentation on RTD (particularly for the options) will require baseclasses to be present. Previously with API documentation, autodoc was able to mock baseclasses since it only needed to access the docstrings, but now with the options documentation a class instance must be initialized which requires baseclasses to access the `defaultOptions` class attribute.
Note that I have changed the PyPI package name to …
> Preparation for PyPI release

- baseclasses/utils.py
- tests/test_BaseSolver.py
As soon as #32 was merged I realized I could've added a better test. Now the test checks that the suggested option for `invalidOption` was `intOption`.
I have also updated the `Error` class slightly:
- added a `message` field to store the _unformatted_ message that's passed in
- instead of manually printing the message, pass it to the parent class for printing. That way, you can do things like
```
try:
<some code>
except Exception as e:
print(f"Something went wrong! The exception raised was {str(e)}")
```
or similar where you can access the _formatted_ message via `str(e)`, and unformatted message via `e.message`.
Explain the steps needed to test the new code to verify that it does indeed address the issue …
> Updated error class and tests

- baseclasses/BaseSolver.py
- baseclasses/utils.py
- tests/test_BaseSolver.py
- tests/test_CaseInsensitve.py
Fixed many bugs:
- The logic in `getModifiedOptions` was incorrect, this is now fixed.
- CaseInsensitive classes had bugs in implementation in a few places. In particular, `a.update(b)` did not work as expected when either `a` or `b` were not case insensitive. This is now fixed along with a couple of other things like comparisons.
I added many new tests, which are now refactored to be more self-contained unit tests.
> Various bug fixes

- .github/test_real.sh
This PR tests the `AGENT_NAME` environment variable, which is available on Azure to identify the agent pool used. Based on this we can set the `-n` parameter for `testflo`, between Azure and build bot.
> Update test script

- README.md
- doc/index.rst
Add conda-forge badge to README.md. Perhaps the docs should also be updated to reflect that this now be pip or conda installed from PyPi and conda-forge, respectively.
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.
> Add conda-forge badge to README.md

- .github/azure-pipelines.yaml
- .github/test_real.sh
- README.md
- baseclasses/pyAero_solver.py
> Add coverage

- .flake8
- baseclasses/problems/__init__.py
- baseclasses/problems/pyAero_problem.py
- baseclasses/problems/pyMission_problem.py
- baseclasses/problems/pyStruct_problem.py
- baseclasses/solvers/__init__.py
- baseclasses/testing/__init__.py
- baseclasses/testing/decorators.py
- baseclasses/utils/__init__.py
- baseclasses/utils/containers.py
- baseclasses/utils/py3Util.py
- doc/BaseRegTest.rst
- doc/BaseSolver.rst
- doc/index.rst
- doc/pyAeroStruct_problem.rst
- doc/pyAero_problem.rst
- doc/pyAero_solver.rst
- doc/pyMission_problem.rst
- doc/pyStruct_problem.rst
- doc/pyWeight_problem.rst
- doc/regression_example.rst
- doc/utils.rst
- tests/test_BaseRegTest.py
- fixed flake8 issues
- updated docs layout due to #64
- added `__all__` to the module init files
N/A
> Update flake8 and docs

- baseclasses/__init__.py
- baseclasses/solvers/BaseSolver.py
- baseclasses/utils/utils.py
Based on the discussion in https://github.com/mdolab/baseclasses/pull/71 this PR updates the `utils.pp` function, and refactors the `BaseSolver.pp` implementation in https://github.com/mdolab/baseclasses/pull/71
> Refactoring pp in BaseSolver to use an updating pp in utils.

- baseclasses/solvers/pyAero_solver.py
This PR accompanies mdolab/adflow#192 and should be merged before it.
> kwargs for AeroSolver addPointSet

- baseclasses/problems/pyAero_problem.py
Related to mdolab/adflow#209
Should be quick
> Clarified that AeroProblem angles are in degrees

- doc/requirements.txt
- setup.py
As per title, now if the user wants to build the documentation locally, they can set all the dependencies using `pip install .[docs]`
as soon as tests pass?
> added docs require

- tests/test_fileIO.py
The conda tests revealed once again that one test fails when mpi4py is unavailable. I've fixed it here.
A few days
> Fix test for when mpi4py is unavailable

- baseclasses/testing/pyRegTest.py
- tests/test_BaseRegTest.py
I added a function to compare equality of objects such as list of strings. This means that we can now store stuff for exact comparison. Currently only lists of strings are supported, but we can add more in the future.
No rush
I added a test for this.
> Added function to compare list of strings

- baseclasses/testing/pyRegTest.py
- tests/test_BaseRegTest.py
This PR improves #82 by using `numpy.can_cast` to test whether we can use `numpy.testing.assert_allclose` or we should test for equality instead.
This more general approach now allows for other JSON-serializable objects to be stored and compared in the reference files. A good example would be a single string value.
2-3 days.
I added a test.
> Better equality testing

- baseclasses/testing/pyRegTest.py
The changes from #84 do not work if the values are complex. This PR fixes it by making the dtype check broader, such that all numeric dtypes are accepted. While we should really not be testing complex numbers, this PR does allow for it.
ASAP.
Existing test coverage is okay. I tried to add a test for complex numbers, but it's tricky because when we write to the ref file, they are automatically cast to real.
> Better dtype check

- baseclasses/problems/FluidProperties.py
- baseclasses/problems/ICAOAtmosphere.py
- baseclasses/problems/pyAeroStruct_problem.py
- baseclasses/problems/pyAero_problem.py
- baseclasses/problems/pyFieldPerformance_problem.py
- baseclasses/problems/pyLG_problem.py
- baseclasses/problems/pyMission_problem.py
- baseclasses/problems/pyStruct_problem.py
- baseclasses/problems/pyWeight_problem.py
- baseclasses/solvers/BaseSolver.py
- baseclasses/solvers/pyAero_solver.py
- baseclasses/utils/solverHistory.py
- tests/test_BaseSolver.py
> Black style fix

- baseclasses/problems/pyAero_problem.py
- tests/test_AeroProblem.py
- Adds a `getDesignVars` method that returns the current design variable values for an aeroproblem.
- Fixes a bug in the logic that determines what the valid DVs for the aeroproblem. Only flow conditions that are passed as inputs when creating the aeroproblem are valid DVs, however the previous logic would mark any flow properties that are created based on the ones passed as inputs as also valid. For example, if you define an aeroproblem using reynolds number, mach number and temperature then pressure would incorrectly be added to the list of possible DVs because it is added as an attribute of the aeroproblem. This means you could call `addDV` to add a pressure DV and an error would only be raised when you call `setDesignVars`. With the new logic, this error is caught in `addDV`
- Adds a …
> Add `getDesignVars` method for AeroProblem

- baseclasses/__init__.py
- tests/test_SolverHistory.py
Add support for numpy2. No changes to library code but I did have to update one test. Also bumping version to release on conda-forge.
1-2 days
Existing tests pass
> Support numpy2

- baseclasses/__init__.py
- setup.py
This PR updates the minimum packages requirements and version of baseclasses based on [this GitHub issue](https://github.com/mdolab/docker/issues/271#issue-2708438008)
> Update package requirements
